### ISSUE TITLE
ImportError: No module named pylibmpsse

### ISSUE THREAD

**Issue by nikhilh-20** [devttys0/libmpsse#38]
I'm new to IoT firmware RE and I was following the blog at https://nvisium.com/blog/2019/08/07/extracting-firmware-from-iot-devices.html.

The author mentioned the following command:
`sudo python spiflash.py -s 15000000 -r firmware.bin`

I git cloned this repository, ran the above command and got the error:
`ImportError: No module named mpsse`

So, I ran the `mpsse.py` file in the `src` directory and got the error:
`ImportError: No module named pylibmpsse`

What is this library? How do I get `spiflash.py` to execute?

More information:

```
root@malnet:/opt/libmpsse/src/examples# python spiflash.py 
Traceback (most recent call last):
  File "spiflash.py", line 3, in <module>
    from mpsse import *
ImportError: No module named mpsse

root@malnet:/opt/libmpsse/src# python mpsse.py 
Traceback (most recent call last):
  File "mpsse.py", line 1, in <module>
    import pylibmpsse as _mpsse
ImportError: No module named pylibmpsse

root@malnet:/opt/libmpsse/src# python examples/spiflash.py 
Traceback (most recent call last):
  File "examples/spiflash.py", line 3, in <module>
    from mpsse import *
ImportError: No module named mpsse

root@malnet:/opt/libmpsse/src/examples# uname -a
Linux malnet 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-5kali1 (2019-06-20) x86_64 GNU/Linux

root@malnet:/opt/libmpsse/src/examples# python -V
Python 2.7.16
```

**Comment by Brets0150** [comment]
Hello,
Did you resolve this issue? If so how? Running into the same problem myself.

**Comment by whoot** [comment]
> 
> 
> Hello,
> Did you resolve this issue? If so how? Running into the same problem myself.

@Brets0150 The error says it clearly. Just install the missing library ;)
```python2 -m pip install libmpsse```

**Comment by nikhilh-20** [comment]
I don't remember exactly what I did but I think I switched over to using `flashrom` for firmware extraction. @whoot's solution seems simple enough if it works.

**Comment by hassan-salloum** [comment]
Hi guys, i would like to re-open this topic, after a lot of adaptation for the spiflash.py script, to make it work with python3, like:
1- add () for all print""
2- change the exception try from (except GetoptError, e:) to be (except getopt.GetoptError as e:)

Then i tried to run the script and i got this error:
![image](https://github.com/devttys0/libmpsse/assets/26716241/e5158e29-0aa8-4e24-a031-3d73d876b17f)

After many search i didn't succeed to install the libmpss:
![image](https://github.com/devttys0/libmpsse/assets/26716241/ebb3e0c5-96ac-47a0-8f7f-a35e044afd31)

any suggestion please ? i am using kali linux 2023.2
thx

**Comment by whoot** [comment]
As far as I know there is no Python 3 version of libmpsse.
However, you could try this patch here: https://github.com/devttys0/libmpsse/pull/10

**Comment by hassan-salloum** [comment]
@whoot  thanks, well in that case i believe the best approach is to make the script run with python2 on latest kali version (in my case kali 2023.2)

**These are my steps that can be a fix for this issue:**

1- [Change python version system-wide with update-alternatives python to temporary force it on python2 while using the spiflash.py script:](https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux). (Note: don't forget to switch back to your default python version once you finish using the script since your system packages will probably based on the lasted python version.)

2- Then i installed the missing library libmpsse (you need to install first the pip for python2):
```
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
python get-pip.py
python2 -m pip install libmpsse
```

3- Libmpsse requires swig as well as the libftdi and python development packages. as mentioned [here](https://github.com/devttys0/libmpsse/blob/master/docs/INSTALL).

in case you are using latest debian version like kali 2023.2, this command may not work:
![image](https://github.com/devttys0/libmpsse/assets/26716241/47b9976e-841c-4e9d-ba9a-5650e26bc6e7)

so use this instead:
![image](https://github.com/devttys0/libmpsse/assets/26716241/133a0025-e053-4393-99d4-19ccc866865d)


**Result:**
![image](https://github.com/devttys0/libmpsse/assets/26716241/3870442b-a1a8-4587-ac41-12488198d4a4)

![image](https://github.com/devttys0/libmpsse/assets/26716241/081dc3bf-bb0f-42a3-accb-bab3bfcfc227)

To fix this as well : please added (import getopt) to the spiflash.py code
![image](https://github.com/devttys0/libmpsse/assets/26716241/f842da0f-6e64-41bc-901a-0691f962ef73)
like that:
![image](https://github.com/devttys0/libmpsse/assets/26716241/92ce8082-ff42-4509-85c5-79032c0157d6)

**Comment by VraiHack** [comment]
@whoot can you please tell me what i have change here,  the spiflash wasn't capable capture the ID of the flash:
![image](https://github.com/devttys0/libmpsse/assets/26716241/4f4cd21d-5d67-42e9-bd73-c2532167e1f6)

even with flashrom but manually with buspirate i was capable ,

can you please take a look on my issue here: https://github.com/BusPirate/Bus_Pirate/issues/131

Thanks in advance for your time

**Comment by VraiHack** [comment]
@whoot hi again, what is the max frequency i can assign with the spiflash.py with -f option , is that depend as well on the adapter spead?

**Comment by whoot** [comment]
> @whoot thanks, well in that case i believe the best approach is to make the script run with python2 on latest kali version (in my case kali 2023.2)
> 
> **These are my steps that can be a fix for this issue:**
> 
> 1- [Change python version system-wide with update-alternatives python to temporary force it on python2 while using the spiflash.py script:](https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux). (Note: don't forget to switch back to your default python version once you finish using the script since your system packages will probably based on the lasted python version.)

This should not be necessary. Kali has python2 already installed.

**Comment by hassan-salloum** [comment]
@whoot Yes its necessary, **_and my steps not about installing python2_**. You have to read with attention my steps. But i will explain:
1- new version kali linux once you install, dominate python3. and in case you need to use python2 you need to update-alternative (sometime)
2- pip for python2 not installed by default on new kali version, you have to install.

None of my steps was without a POC (you can see the screenshoot ! )

The best thing you can do is to install kali linux 2023.2 VM and try with python2 to run the spiflash script directly without my steps and you will understand the struggle i passed.

**Comment by whoot** [comment]
I just said that you should use python2, because there is no support for python3.
You got it working, so everything is fine, right?
